/*
INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, ESTADO) VALUES(1, 'CADEIRA BLUE', 'CADEIRA DE MADEIRA AZUL', 45.23, 'SP');
INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, ESTADO) VALUES('2, 'CHURRASQUEIRA AP', 'CHURRASQUEIRA PARA APARTAMENTO', 278.10, 'GO');
INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, ESTADO) VALUES(3, 'CAMISA BEL', 'CAMISETA FINA ESTAMPA AMARELA', 520.33, 'RJ');
INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, ESTADO) VALUES(4, 'FRIGOBAR NITRO', 'FRIGOBAR DE ACO ESCOVADO', 1467.90, 'SP');
*/

SELECT * FROM PEDIDO ;
SELECT * FROM PRODUTO ;
SELECT * FROM ITEM_PEDIDO;
SELECT * FROM INFO_FORNECEDOR;
